export const DEFAULT_USER_AVATAR =
	"https://wgfxomkpkpixkczgjjko.supabase.co/storage/v1/object/public/avatars/userAvatar.png?t=2023-11-03T12%3A24%3A02.444Z";

export const PAGE_SIZE = 5;

// export const BASIC_INGREDIENTS_LIST = [
// 	"Jabłko",
// 	"Gruszka",
// 	"Wiśnia",
// 	"Śliwka",
// 	"Brzoskwinia",
// 	"Morela",
// 	"Mango",
// 	"Banan",
// 	"Kiwi",
// 	"Arbuz",
// 	"Grejpfrut",
// 	"Pomarańcza",
// 	"Cytryna",
// 	"Mandarynka",
// 	"Granat",
// 	"Malina",
// 	"Jeżyna",
// 	"Porzeczka",
// 	"Truskawka",
// 	"Ananas",
// 	"Kiwi",
// 	"Winogrono",
// 	"Jagoda",
// 	"Borówka",
// 	"Karambola ",
// 	"Liczi",
// 	"Awokado",
// 	"Pomelo",
// 	"Nektarynka",
// 	"Persymona",
// 	"Granat",
// 	"Papaja",
// 	"Gujawa",
// 	"Passiflora ",
// 	"Daktyle",
// 	"Figi",
// 	"Kasztan",
// 	"Malakat ",
// 	"Jabłko szampion",
// 	"Kiwi zlata",
// 	"Marakuja purpurowa",
// 	"Mango Alphonso",
// 	"Czarna porzeczka",
// 	"Czerwona porzeczka",
// 	"Limonka",
// 	"Aronia",
// 	"Czereśnia",
// 	"Mirabelka",
// 	"Pawpaw",
// 	"Czarna jagoda",
// 	"Głóg",
// 	"Niedźwiedzia jagoda",
// 	"Czarny bez",
// 	"Żurawina",
// 	"Feijoa",
// 	"Nashi ",
// 	"Kiwano ",
// 	"Pigwa",
// 	"Płoski brzoskwiniowiec",
// 	"Chanar ",
// 	"Tamarillo",
// 	"Rambutan",
// 	"Czarny bez",
// 	"Szefalonia ",
// 	"Kalafior",
// 	"Japara ",
// 	"Lulo",
// 	"Słodkie ziemniaki",
// 	"Czereśnia ptasia",
// 	"Kaktus opuncja",
// 	"Arbutus ",
// 	"Durian",
// 	"Jujuba ",
// 	"Kiwi czerwone",
// 	"Mandarynka satsuma",
// 	"Kaki ",
// 	"Kiwi złote",
// 	"Różanka",
// 	"Pigwowiec japoński",
// 	"Kakadu plum",
// 	"Melon kantalupa",
// 	"Czarna porzeczka",
// 	"Czarne maliny",
// 	"Czerwone maliny",
// 	"Oliwka",
// 	"Awokado zielone",
// 	"Kiwi Hayward",
// 	"Lucuma",
// 	"Mango Kent",
// 	"Mangostan",
// 	"Ogranic",
// 	"Głóg jednoszyjkowy",
// 	"Limonka kafir",
// 	"Kaki fuyu",
// 	"Kiwi Arctic",
// 	"Guawa chilijska",
// 	"Cytryna yuzu",
// 	"Durian zaostrzony",
// 	"Nektarynka saturn",
// 	"Tamarindo",
// 	"Mangaba",
// 	"Noni",
// 	"Salak",
// 	"Ugli",
// 	"Physalis ",
// 	"Jabłko paradise",
// 	"Jabłko perskie",
// 	"Szczypiorek chiński",
// 	"Cudowne owoce",
// 	"Owoce goji",
// 	"Kizil",
// 	"Kiviak",
// 	"Marchew",
// 	"Ziemniak",
// 	"Cebula",
// 	"Pomidor",
// 	"Sałata",
// 	"Ogórek",
// 	"Papryka",
// 	"Brokuły",
// 	"Kalafior",
// 	"Szpinakani",
// 	"Czosnek",
// 	"Bakłażan",
// 	"Rzodkiewka",
// 	"Seler",
// 	"Pasternak",
// 	"Por",
// 	"Brukselka",
// 	"Kukurydza",
// 	"Rzepa",
// 	"Kapusta",
// 	"Dynia",
// 	"Fasola",
// 	"Groszek",
// 	"Szparagi",
// 	"Kalarepa",
// 	"Cukinia",
// 	"Karczoch",
// 	"Rukola",
// 	"Papryka chili",
// 	"Pomidor cherry",
// 	"Rzepa japońska",
// 	"Jarmuż",
// 	"Kiełki fasoli",
// 	"Dynia cukiniowa",
// 	"Rzepa chińska",
// 	"Czosnek niedźwiedzi",
// 	"Cebula dymka",
// 	"Pęczak",
// 	"Pieczarki",
// 	"Kalarepka",
// 	"Batat",
// 	"Papryka jalapeño",
// 	"Rzepa czarna",
// 	"Szczypiorek",
// 	"Por wietnamski",
// 	"Kalarepa chińska",
// 	"Bakłażan japoński",
// 	"Kapusta pak choi",
// 	"Bakłażan chiński",
// 	"Cebula czerwona",
// 	"Cebula biała",
// 	"Cebula żółta",
// 	"Marchewka fioletowa",
// 	"Marchewka żółta",
// 	"Marchewka biała",
// 	"Cebula szalotka",
// 	"Cebula perłowa",
// 	"Słodki ziemniak",
// 	"Karczoch jerozolimski",
// 	"Fasolka szparagowa",
// 	"Kapusta pekińska",
// 	"Kapusta włoska",
// 	"Kapusta czerwona",
// 	"Kapusta kiszona",
// 	"Kiełki bambusa",
// 	"Kiełki lucerny",
// 	"Kiełki rzodkiewki",
// 	"Kiełki soczewicy",
// 	"Kiełki fasoli mung",
// 	"Kiełki dyni",
// 	"Kiełki brokuła",
// 	"Kiełki cebuli",
// 	"Kiełki pszenicy",
// 	"Kiełki rzepaku",
// 	"Kiełki słonecznika",
// 	"Kiełki grochu",
// 	"Kiełki konopi",
// 	"Rzepa żółta",
// 	"Dynia hokkaido",
// 	"Dynia piżmowa",
// 	"Kukurydza cukrowa",
// 	"Kukurydza popcorn",
// 	"Rzepak",
// 	"Rzepa czarna",
// 	"Rzepa czerwona",
// 	"Rzepa zielona",
// 	"Rzepa pomarańczowa",
// 	"Rzepa żółta",
// 	"Rzepa fioletowa",
// 	"Kukurydza czerwona",
// 	"Szparagi zielone",
// 	"Szparagi białe",
// 	"Kapusta chińska",
// 	"Kalarepa",
// 	"Bakłażan japoński ",
// 	"Kapusta pak choi",
// 	"Rzodkiew oleista",
// 	"Kalarepa rzymska",
// 	"Batat japoński",
// 	"Bakłażan biały",
// 	"Rzodkiewka czarna",
// 	"Rzodkiewka japońska",
// 	"Dynia piżmowa butternut",
// 	"Dynia dębowa",
// 	"Dynia acorn",
// 	"Karczoch francuski",
// 	"Jarmuż chiński",
// 	"Cukinia patisson",
// 	"Bakłażan czekoladowy",
// 	"Bakłażan zebra",
// 	"Bakłażan japoński",
// 	"Bakłażan tygrysi",
// 	"Por japoński",
// 	"Por chiński",
// 	"Kalarepa rzymska lila",
// 	"Czosnek niedźwiedzi japoński",
// 	"Brukselka czerwona",
// 	"Batat japoński",
// 	"Pieczarki portobello",
// 	"Pieczarki shiitake",
// 	"Kapusta kiszonka",
// 	"Rzodkiewka daikon",
// 	"Kukurydza fioletowa",
// 	"Seler korzeniowy",
// 	"Seler naciowy",
// 	"Papryka pimiento",
// 	"Papryka piquillo",
// 	"Dynia duch",
// 	"Szpinak malabarski",
// 	"Jarmuż dziki",
// 	"Kalarepa wodna",
// 	"Rzepa czarna hiszpańska",
// 	"Kiełbasa biała",
// 	"Kiełbasa kabanos",
// 	"Kiełbasa krakowska",
// 	"Kiełbasa myśliwska",
// 	"Kiełbasa wiejska",
// 	"Kiełbasa kiełbasa",
// 	"Kiełbasa grillowa",
// 	"Kiełbasa śląska",
// 	"Kiełbasa podwawelska",
// 	"Kiełbasa chorizo",
// 	"Kiełbasa kabanosy",
// 	"Kiełbasa surowa",
// 	"Kiełbasa parówkowa",
// 	"Kiełbasa cienka",
// 	"Kiełbasa węgierska",
// 	"Kiełbasa wieprzowa",
// 	"Kiełbasa drobiowa",
// 	"Kiełbasa cielęca",
// 	"Kiełbasa krótka",
// 	"Kiełbasa długa",
// 	"Kiełbasa krótka z czosnkiem",
// 	"Kiełbasa długa z czosnkiem",
// 	"Kiełbasa grillowa z serem",
// 	"Kiełbasa śląska z czosnkiem",
// 	"Kiełbasa krakowska parzona",
// 	"Kiełbasa śląska parzona",
// 	"Kiełbasa wiejska parzona",
// 	"Kiełbasa grillowa parzona",
// 	"Kiełbasa węgierska parzona",
// 	"Kiełbasa myśliwska parzona",
// 	"Kiełbasa krakowska suszona",
// 	"Kiełbasa myśliwska suszona",
// 	"Kiełbasa węgierska suszona",
// 	"Kiełbasa chorizo suszona",
// 	"Kiełbasa krótka suszona",
// 	"Kiełbasa długa suszona",
// 	"Kiełbasa krótka z czosnkiem suszona",
// 	"Kiełbasa długa z czosnkiem suszona",
// 	"Kiełbasa śląska z czosnkiem suszona",
// 	"Kiełbasa grillowa z serem suszona",
// 	"Duroc",
// 	"Hampshire",
// 	"Yorkshire",
// 	"Tamworth",
// 	"Berkshire",
// 	"Mangalica",
// 	"Iberico",
// 	"Kurobuta",
// 	"Cinta Senese",
// 	"Pietrain",
// 	"Bazna",
// 	"Gloucestershire Old Spot",
// 	"Red Wattle",
// 	"Large Black",
// 	"Dalland",
// 	"Mora Romagnola",
// 	"Poland China",
// 	"Saddleback",
// 	"Struś",
// 	"Kangurowina",
// 	"Bażant",
// 	"Dziczyzna",
// 	"Zebra",
// 	"Aligator",
// 	"Kangur",
// 	"Wąż",
// 	"Żółw",
// 	"Krokodyl",
// 	"Żyrafie mięso",
// 	"Skorpion",
// 	"Żuk bambusowy",
// 	"Mrówka",
// 	"Krab",
// 	"Homar",
// 	"Krewetki",
// 	"Kalmary",
// 	"Małże",
// 	"Ostrygi",
// 	"Morszczuk",
// 	"Halibut",
// 	"Łosoś",
// 	"Tuńczyk",
// 	"Makrela",
// 	"Sardynki",
// 	"Śledź",
// 	"Szprot",
// 	"Ślimaki",
// 	"Żabie uda",
// 	"Polędwica wołowa",
// 	"Befsztyk wołowy",
// 	"Przywarta wołowa",
// 	"Żebra wołowe",
// 	"Tatar wołowy",
// 	"Schab wieprzowy",
// 	"Karkówka wieprzowa",
// 	"Polędwica wieprzowa",
// 	"Boczek wieprzowy",
// 	"Szynka wieprzowa",
// 	"Żeberka wieprzowe",
// 	"Kiełbasa wieprzowa",
// 	"Skrzydełka z kurczaka",
// 	"Noga wieprzowa",
// 	"Golonka Wieprzowa",
// 	"Nóżki z kurczaka",
// 	"Piersi z kurczaka",
// 	"Karczek z kurczaka",
// 	"Podudzia z kurczaka",
// 	"Parówki tradycyjne",
// 	"Parówki drobiowe",
// 	"Parówki wieprzowe",
// 	"Parówki cielęce",
// 	"Parówki krakowskie",
// 	"Parówki wiedeńskie",
// 	"Parówki szynkowe",
// 	"Parówki cienkie",
// 	"Parówki grube",
// 	"Parówki z serem",
// 	"Parówki z ziołami",
// 	"Parówki z czosnkiem",
// 	"Parówki z kurkumą i curry",
// 	"Parówki z papryką",
// 	"Parówki z kiełbasą śląską",
// 	"Parówki z kabanosem",
// 	"Parówki grillowe",
// 	"Parówki z indyka",
// 	"Parówki wegańskie",
// 	"Parówki z jagnięciny",
// 	"Parówki z dziczyzny",
// 	"Parówki z drobiu i szpinakiem",
// 	"Parówki z rybą",
// 	"Parówki z cielęciną",
// 	"Parówki z łososiem",
// 	"Parówki z tofu",
// 	"Parówki z krewetkami",
// 	"Parówki z łososiem i koperkiem",
// 	"Parówki z kaczką",
// 	"Parówki z kurczakiem i ziołami",
// 	"Parówki z kiełbasą chorizo",
// 	"Parówki z kiełbasą krakowską",
// 	"Parówki z kiełbasą myśliwską",
// 	"Parówki z kiełbasą węgierską",
// 	"Parówki z kiełbasą śląską",
// 	"Parówki z kiełbasą grillową",
// 	"Parówki z kiełbasą podwawelską",
// 	"Parówki z kiełbasą wiejską",
// 	"Parówki z kiełbasą cienką",
// 	"Parówki z kiełbasą długą",
// 	"Mięso mielone wieprzowe",
// 	"Mięso mielone wołowe",
// 	"Mięso mielone drobiowe",
// 	"Mięso mielone cielęce",
// 	"Mięso mielone jagnięce",
// 	"Mięso mielone wołowo-wieprzowe",
// 	"Mięso mielone kaczki",
// 	"Mięso mielone indyka",
// 	"Mięso mielone kurczaka",
// 	"Mięso mielone cielęce i wieprzowe",
// 	"Mięso mielone z indyka i wieprzowiny",
// 	"Mięso mielone z łososia",
// 	"Mięso mielone z krewetek",
// 	"Mięso mielone wegańskie",
// 	"Mięso mielone z dziczyzny",
// 	"Mięso mielone z kraba",
// 	"Mięso mielone z łososia i szpinakiem",
// 	"Mięso mielone z kiełbasy",
// 	"Mięso mielone z tofu",
// 	"Olej rzepakowy",
// 	"Olej słonecznikowy",
// 	"Olej oliwkowy",
// 	"Olej kokosowy",
// 	"Olej lniany",
// 	"Olej sezamowy",
// 	"Olej awokado",
// 	"Olej z pestek winogron",
// 	"Olej orzechowy",
// 	"Olej rybny",
// 	"Oliwa z oliwek",
// 	"Ocet balsamiczny",
// 	"Ocet winny",
// 	"Ocet jabłkowy",
// 	"Ocet winny",
// 	"Ocet z białego wina",
// 	"Ocet z czerwonego wina",
// 	"Ocet ryżowy",
// 	"Ocet z koniczyny czerwonej",
// 	"Ocet białego wina",
// 	"Ocet cytrynowy",
// 	"Ocet truflowy",
// 	"Ocet malinowy",
// 	"Ocet ziołowy",
// 	"Ocet balsamiczny z Modeny",
// 	"Ocet balsamiczny Tradizionale",
// 	"Ocet z sherry",
// 	"Ocet z białego wina musującego",
// 	"Ocet z czerwonego wina musującego",
// 	"Pieprz czarny",
// 	"Pieprz biały",
// 	"Pieprz czerwony (papryka chilli)",
// 	"Pieprz różowy",
// 	"Kminek",
// 	"Koper",
// 	"Kolendra",
// 	"Kardamon",
// 	"Cynamon",
// 	"Gałka muszkatołowa",
// 	"Imbir",
// 	"Kurkuma",
// 	"Szafran",
// 	"Czosnek granulowany",
// 	"Czosnek świeży",
// 	"Czosnek w proszku",
// 	"Cebula granulowana",
// 	"Cebula świeża",
// 	"Cebula w proszku",
// 	"Bazylia",
// 	"Oregano",
// 	"Rozmaryn",
// 	"Tymianek",
// 	"Estragon",
// 	"Majeranek",
// 	"Lubczyk",
// 	"Pietruszka",
// 	"Natka pietruszki",
// 	"Koperek",
// 	"Seler naciowy",
// 	"Papryka słodka",
// 	"Papryka ostra",
// 	"Papryka w proszku",
// 	"Papryka wędzona",
// 	"Zioła prowansalskie",
// 	"Szczypiorek",
// 	"Liść laurowy",
// 	"Liście laurowe",
// 	"Curry",
// 	"Ketchup",
// 	"Musztarda",
// 	"Majonez",
// 	"Papryka chili",
// 	"Chilli cayenne",
// 	"Sos sojowy",
// 	"Sos teriyaki",
// 	"Sos barbecue",
// 	"Sos śmietanowo-ziemniaczany",
// 	"Sos curry",
// 	"Sos tzatziki",
// 	"Sos guacamole",
// 	"Sos salsa",
// 	"Sos jogurtowy ziołowy",
// 	"Sos amerykański",
// 	"Sos meksykański",
// 	"Sos czosnkowy",
// 	"Sól",
// 	"Sól morska",
// 	"Sól himalajska",
// 	"Sól czosnkowa",
// 	"Sól cebulowa",
// 	"Sól ziołowa",
// 	"Sól pieprzowa",
// 	"Sól curry",
// 	"Sól cytrynowa",
// 	"Sól pieprzowo-cytrynowa",
// 	"Sól ziołowo-cytrynowa",
// 	"Sól ziołowo-cytrynowa-pieprzowa",
// 	"Sól oregano-cytrynowa",
// 	"Sól chili",
// 	"Sól cynamonowa",
// 	"Mleko bez laktozy",
// 	"Mleko 0.5%",
// 	"Mleko 1%",
// 	"Mleko 1.5%",
// 	"Mleko 2%",
// 	"mleko 3.2&",
// 	"Mleko krowie",
// 	"Mleko kozie",
// 	"Mleko owcze",
// 	"Mleko sojowe",
// 	"Mleko migdałowe",
// 	"Mleko kokosowe",
// 	"Mleko ryżowe",
// 	"Mleko konopne",
// 	"Ser cheddar",
// 	"Ser gouda",
// 	"Ser camembert",
// 	"Ser brie",
// 	"Ser feta",
// 	"Ser parmezan",
// 	"Ser mozzarella",
// 	"Ser błękitny (blue cheese)",
// 	"Ser pleśniowy",
// 	"Ser kozí",
// 	"Ser owczy",
// 	"Ser koryciński",
// 	"Ser żółty",
// 	"Ser śmietankowy",
// 	"Ser kremowy",
// 	"Ser kazeinowy",
// 	"Ser cottage",
// 	"Ser ricotta ",
// 	"Ser panela",
// 	"Ser halloumi",
// 	"Ser góralski",
// 	"Ser kwasowy",
// 	"Ser raclette",
// 	"Ser provolone",
// 	"Ser edam",
// 	"Ser gorgonzola",
// 	"Ser gruyère",
// 	"Ser ementaler",
// 	"Ser górski",
// 	"Ser koryciński",
// 	"Ser topiony",
// 	"Jajka kurze",
// 	"Jajka kacze",
// 	"Jajka przepiórcze",
// 	"Śmietana kremówka 30% ",
// 	"Śmietana kremówka 36%",
// 	"Śmietana 18%",
// 	"Śmietana 12%",
// 	"Śmietanka kokosowa",
// 	"Płatki owsiane",
// 	"Płatki pszenne",
// 	"Płatki kukurydziane",
// 	"Płatki ryżowe",
// 	"Płatki jaglane",
// 	"Płatki gryczane",
// 	"Płatki orkiszowe",
// 	"Płatki quinoa",
// 	"Płatki jaglane",
// 	"Płatki amarantusowe",
// 	"Jogurt naturalny",
// 	"Jogurt grecki",
// 	"Jogurt grecki gęsty",
// 	"Jogurt owocowy",
// 	"Kefir",
// 	"Maślanka",
// 	"Maślanka kwaszona",
// 	"Serwatka",
// 	"Masło",
// 	"Margaryna",
// 	"Śmietanka do kawy",
// 	"Masło orzechowe",
// 	"Masło migdałowe",
// 	"Masło kokosowe",
// 	"Masło sojowe",
// 	"Masło z orzechów nerkowca",
// 	"Masło z orzechów włoskich",
// 	"Masło z pistacji",
// 	"Masło klarowane (ghee)",
// 	"Masło ziołowe",
// 	"Masło truflowe",
// 	"Masło kakaowe",
// 	"Konfitura truskawkowa",
// 	"Miód pszczeli",
// 	"Syrop klonowy",
// 	"Syrop agawowy",
// 	"Syrop daktylowy",
// 	"Dżem brzoskwiniowy",
// 	"Dżem malinowy",
// 	"Dżem śliwkowy",
// 	"Dżem z dzikiej róży",
// 	"Dżem z aronii",
// 	"Dżem z borówek",
// 	"Dżem z pigwy",
// 	"Woda",
// 	"Woda gazowana",
// 	"Woda średniogazowana",
// 	"Kawa",
// 	"Herbata czarna",
// 	"Herbata zielona",
// 	"Herbata owocowa",
// 	"Herbata ziołowa",
// 	"Herbata miętowa",
// 	"Herbata imbirowa",
// 	"Kawa latte",
// 	"Cappuccino",
// 	"Espresso",
// 	"Americano",
// 	"Mocha",
// 	"Frappe",
// 	"Cola",
// 	"Cola light",
// 	"Cola zero",
// 	"Sprite",
// 	"Fanta",
// 	"Pepsi",
// 	"Lemoniada",
// 	"Herbata mrożona",
// 	"Kawa mrożona",
// 	"Koktajl owocowy",
// 	"Smoothie",
// 	"Mleko",
// 	"Mleko czekoladowe",
// 	"Mleko waniliowe",
// 	"Mleko truskawkowe",
// 	"Mleko bananowe",
// 	"Shake białkowy",
// 	"Napój izotoniczny",
// 	"Napój energetyczny",
// 	"Sok pomarańczowy",
// 	"Sok jabłkowy",
// 	"Sok grejpfrutowy",
// 	"Sok marchwiowy",
// 	"Sok truskawkowy",
// 	"Sok malinowy",
// 	"Sok aronii",
// 	"Koktajl proteinowy",
// 	"Napój migdałowy",
// 	"Napój sojowy",
// 	"Napój ryżowy",
// 	"Napój kokosowy",
// 	"Napój migdałowo-kokosowy",
// 	"Napój owsiany",
// 	"Napój marchewkowo-jabłkowy",
// 	"7UP",
// 	"Mirinda",
// 	"Mountain Dew",
// 	"Dr Pepper",
// 	"Pepsi Twist",
// 	"Pepsi Lime",
// 	"Pepsi Cherry",
// 	"Pepsi Vanilla",
// 	"Schweppes",
// 	"Tonic",
// 	"Ginger Ale",
// 	"Coca-Cola Cherry",
// 	"Coca-Cola Vanilla",
// 	"Coca-Cola Zero Sugar",
// 	"Coca-Cola Light",
// 	"Pepsi Max",
// 	"Pepsi Max Lime",
// 	"Pepsi Max Cherry",
// 	"Pepsi Max Vanilla",
// 	"Sprite Zero",
// 	"Fanta Zero",
// 	"Red Bull",
// 	"Monster Energy",
// 	"Rockstar Energy",
// 	"Lucozade",
// 	"Lipton Ice Tea",
// 	"Nestea",
// 	"Arizona Iced Tea",
// 	"Aquarius",
// 	"Powerade",
// 	"Wódka",
// 	"Scotch whisky",
// 	"Irish whiskey",
// 	"Bourbon",
// 	"Rye whiskey",
// 	"Tennessee whiskey",
// 	"Canadian whisky",
// 	"Japanese whisky",
// 	"Biały rum",
// 	"Ciemny rum",
// 	"Brandy",
// 	"Cognac",
// 	"Armagnac",
// 	"Pisco",
// 	"Gin",
// 	"Tequila srebrna",
// 	"Tequila złota",
// 	"Mezcal",
// 	"Triple sec",
// 	"Amaretto",
// 	"Baileys Irish Cream",
// 	"Cointreau",
// 	"Grand Marnier",
// 	"Kahlúa",
// 	"Rakija",
// 	"Grappa",
// 	"Aquavit",
// 	"Slivovitz",
// 	"Schnapps",
// 	"Aguardiente",
// 	"Baijiu",
// 	"Soju",
// 	"Shochu",
// 	"Arak",
// 	"Pastis",
// 	"Ouzo",
// 	"Tuzemák",
// 	"Poitín",
// 	"Horilka",
// 	"Moonshine",
// 	"Piwo Lager",
// 	"Piwo Ale",
// 	"Piwo Stout",
// 	"Piwo Porter",
// 	"Piwo Pilsner",
// 	"Piwo Witbier",
// 	"Piwo Weizenbier",
// 	"Piwo Lambic",
// 	"Piwo IPA",
// 	"Czerwone wino",
// 	"Białe wino",
// 	"Różowe wino",
// 	"Szampan",
// 	"Prosecco",
// 	"Cava",
// 	"Port",
// 	"Sherry",
// 	"Marsala",
// 	"Madeira",
// 	"Wino czerwone słodkie",
// 	"Wino czerwone półsłodkie",
// 	"Wino czerwone półwytrawne",
// 	"Wino czerwone wytrawne",
// 	"Wino białe słodkie",
// 	"Wino białe półsłodkie",
// 	"Wino białe półwytrawne",
// 	"Wino białe wytrawne",
// 	"Wino różowe słodkie",
// 	"Wino różowe półsłodkie",
// 	"Wino różowe półwytrawne",
// 	"Wino różowe wytrawne",
// 	"Mąka grahamowa",
// 	"Mąka orkiszowa",
// 	"Mąka owsiana",
// 	"Mąka jaglana",
// 	"Mąka ryżowa",
// 	"Mąka ziemniaczana",
// 	"Mąka tapiokowa",
// 	"Mąka amarantusowa",
// 	"Mąka chia",
// 	"Mąka konopna",
// 	"Mąka kwaszeniowa",
// 	"Mąka orzechowa",
// 	"Mąka z czerwonej soczewicy",
// 	"Mąka z ciecierzycy prażonej",
// 	"Mąka chleba żytniego",
// 	"Kasza gryczana prażona",
// 	"Kasza jaglana prażona",
// 	"Kasza żytnia grahamka",
// 	"Kasza jaglana biała",
// 	"Kasza gryczana biała",
// 	"Kasza orkiszowa niepalona",
// 	"Kasza manna pszenna",
// 	"Kasza pęczak",
// 	"Kasza amarantusowa",
// 	"Kasza jaglana prażona",
// 	"Ryż basmati biały",
// 	"Ryż jaśminowy biały",
// 	"Ryż dziki czarny",
// 	"Ryż dziki brązowy",
// 	"Ryż jasny",
// 	"Ryż czarny",
// 	"Ryż biały",
// 	"Ryż brązowy długoziarnisty",
// 	"Ryż biały krótkoziarnisty",
// 	"Ryż parabolowany biały",
// 	"Ryż Arborio biały",
// 	"Makaron sojowy",
// 	"Makaron ryżowy biały",
// 	"Makaron kukurydziany bezglutenowy",
// 	"Makaron jajeczny",
// 	"Makaron gryczany bezglutenowy",
// 	"Makaron pełnoziarnisty",
// 	"Makaron orkiszowy",
// 	"Makaron konjac",
// 	"Makaron ryżowy brązowy",
// 	"Makaron z ciecierzycy",
// 	"Gnocchi z ziemniaków i szpinaku",
// 	"Gnocchi z patatów",
// 	"Gnocchi z kaszy jaglanej",
// 	"Gnocchi z batatów i kukurydzy",
// 	"Proso żółte",
// 	"Proso białe",
// 	"Amarantus czerwony",
// 	"Amarantus złoty",
// 	"Soczewica czerwona płaska",
// 	"Soczewica czarna beluga",
// 	"Czarny ryż dziki",
// 	"Czarny ryż wietnamski",
// 	"Ryż jaśminowy czarny",
// 	"Ryż jaśminowy czerwony",
// 	"Ryż glutinous czarny",
// 	"Ryż glutinous czerwony",
// 	"Ryż dziki brązowy krótki",
// 	"Ryż dziki brązowy długi",
// 	"Ryż dziki czerwony krótki",
// 	"Ryż dziki czerwony długi",
// 	"Kasza gryczana jasna",
// 	"Kasza gryczana prażona ziołowa",
// 	"Kasza gryczana prażona czosnkowa",
// 	"Kasza gryczana prażona paprykowa",
// 	"Kasza gryczana prażona z warzywami",
// 	"Kasza gryczana z kurkumą",
// 	"Kasza gryczana z koperkiem",
// 	"Kasza jęczmienna niepalona góralska",
// 	"Kasza jęczmienna perłowa góralska",
// 	"Kasza hirska prażona",
// 	"Mąka z konopi pełnoziarnista",
// 	"Mąka gryczana pełnoziarnista",
// 	"Mąka orkiszowa pełnoziarnista",
// 	"Mąka jaglana pełnoziarnista",
// 	"Mąka ryżowa pełnoziarnista",
// 	"Mąka ziemniaczana pełnoziarnista",
// 	"Mąka owsiana pełnoziarnista",
// 	"Mąka amarantusowa pełnoziarnista",
// 	"Mąka chia pełnoziarnista",
// 	"Mąka pszenna pełnoziarnista",
// 	"Mąka typ 00",
// 	"Mąka typ 450 – tortowa",
// 	"Mąka typ 550 – luksusowa",
// 	"Mąka typ 650",
// 	"Mąka typ 750 – chlebowa",
// 	"Mąka typ 1050",
// 	"Mąka typ 1400 – sitkowa",
// 	"Mąka typ 1850 – graham",
// 	"Mąka typ 2000 - razowa",
// 	"Batat japoński (imo)",
// 	"Bakłażan biały",
// 	"Rzodkiewka czarna",
// 	"Rzodkiewka japońska (kaiware)",
// 	"Rzodkiewka daikon",
// 	"Dynia hokkaido",
// 	"Dynia piżmowa butternut",
// 	"Dynia dębowa",
// 	"Dynia acorn",
// 	"Karczoch francuski (artiszok)",
// 	"Jarmuż chiński (gai lan)",
// 	"Cukinia patisson",
// 	"Bakłażan czekoladowy",
// 	"Bakłażan zebra (graffiti)",
// 	"Bakłażan japoński (shikou)",
// 	"Bakłażan tygrysi",
// 	"Por japoński (negi)",
// 	"Por chiński (jiu cai)",
// 	"Kalarepa rzymska lila",
// 	"Czosnek niedźwiedzi japoński",
// 	"Brukselka czerwona",
// 	"Seler korzeniowy",
// 	"Seler naciowy",
// 	"Papryka pimiento",
// 	"Papryka piquillo",
// 	"Dynia duch",
// 	"Szpinak malabarski",
// 	"Jarmuż dziki",
// 	"Kalarepa wodna",
// 	"Rzepa czarna hiszpańska",
// 	"Kardamon",
// 	"Kminek",
// 	"Kolendra mielona",
// 	"Kurkuma",
// 	"Gałka muszkatołowa",
// 	"Ziele angielskie",
// 	"Pieprz czarny",
// 	"Pieprz biały",
// 	"Pieprz różowy",
// 	"Proszek do pieczenia",
// 	"Cukier biały",
// 	"Cukier brązowy",
// 	"Cukier trzcinowy",
// 	"Cukier kokosowy",
// 	"Cukier waniliowy",
// 	"Cukier pudrowy",
// 	"Cukier perłowy",
// 	"Cukier trzcinowy nierafinowany",
// 	"Syrop klonowy",
// 	"Syrop agawowy",
// 	"Syrop daktylowy",
// 	"Melasa",
// 	"Xylitol",
// 	"Erytrytol",
// 	"Stevia",
// 	"Miod pszczeli",
// 	"Cukier z palmy daktylowej",
// 	"Miód wielokwiatowy",
// 	"Miód akacjowy",
// 	"Miód lipowy",
// 	"Miód rzepakowy",
// 	"Miód gryczany",
// 	"Miód manuka",
// 	"Miód koniczynowy",
// 	"Miód lawendowy",
// 	"Miód jałowcowy",
// 	"Miód wrzosowy",
// 	"Miód spadziowy",
// 	"Miód dyniowy",
// 	"Miód cytrynowy",
// 	"Czekolada mleczna",
// 	"Czekolada gorzka",
// 	"Czekolada biała",
// 	"Czekolada deserowa",
// 	"Czekolada nadziewana",
// 	"Czekolada z orzechami",
// 	"Czekolada z bakaliami",
// 	"Czekolada z kawałkami owoców",
// 	"Czekolada truflowa",
// 	"Czekolada rozpuszczalna",
// 	"Czekolada do gotowania",
// 	"Czekolada do pieczenia",
// 	"Czekolada bezcukrowa",
// 	"Kakao",
// 	"Sok z cytryny",
// 	"Sok z limonki",
// 	"Przyprawa do piernika",
// 	"Soda oczyszczona",
// 	"Ogórki kiszone",
// 	"Ogórki konserwowe",
// 	"Ogórki marynowane",
// 	"Ogórki dillowe",
// 	"Ogórki ogórkowe",
// 	"Ogórki małosolne",
// ];
